### PR TITLE
feat: create mock functionality

### PR DESCRIPTION
**Pull request by MASSHUU12**
### What does this PR do?

Implements simple mocking library.

### Why is this change necessary?

[What is Mocking?](https://stackoverflow.com/questions/2665812/what-is-mocking#2666006)

### What issues does this PR fix/close?

N/A

### How was this PR tested?

- manual testing
- unit testing

### Are there any known issues or edge cases?

- [x] "Common Language Runtime detected an invalid program." error when invoking mocked non-void methods.
- [x] "An attempt was made to load a program with an incorrect format. (0x8007000B)" error when invoking mocked ~void~ methods.
- [x] "Object reference not set to an instance of an object." when trying to run mocked methods.

## Checklist:

- [x] Code is formatted correctly.
- [x] Documentation is updated (if necessary).
- [x] Changelog is updated (if necessary).
- [x] All new and existing tests passed (unit and E2E tests).

## To do before merging:

- [x] Write unit tests
- [x] Enhance error handling, provide more context about the failures
- [x] Implement methods to verify that certain methods were called a specific number of times or with specific arguments
- [x] Cache method information to avoid repeated reflection calls
- [x] Ensure that the mock instance is thread-safe
- [x] Provide a method to clear call records

### CODE REVIEW

**Comment by MASSHUU12** [comment]
Hey @OpalSoPL, can you review the changes made in this PR?

Obviously, I still have a lot of things left to do, but I've been agonizing over it for a few days now. I would appreciate it if someone else would take a look at it, evaluate, and possibly suggest changes. I thought implementing this would be trivial, but I was mistaken.

**Comment by OpalSoPL** [comment]
Yes i can, but i need to learn more about mocking, because i don't know what it is

**Comment by MASSHUU12** [comment]
Sure, [here](https://stackoverflow.com/questions/2665812/what-is-mocking#2666006) you can learn in general what that is.

I just found out that .NET includes a `DispatchProxy` class, so I will probably be able to cut the code in half, and I guess I needlessly struggled for so many hours to generate IL code.

**Review by OpalSoPL — APPROVED** [review]
LGTM

**Pull request merged**
